# Generated by Django 5.2.15 on 2026-06-19 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('deposit', '예금'), ('saving', '적금')], max_length=20)),
                ('fin_prdt_cd', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('join_way', models.TextField(blank=True)),
                ('mtrt_int', models.TextField(blank=True)),
                ('spcl_cnd', models.TextField(blank=True)),
                ('join_deny', models.CharField(blank=True, max_length=20)),
                ('join_member', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('dcls_month', models.CharField(max_length=6)),
                ('dcls_strt_day', models.CharField(blank=True, max_length=8)),
                ('dcls_end_day', models.CharField(blank=True, max_length=8)),
                ('fin_co_subm_day', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.bank')),
            ],
            options={
                'unique_together': {('bank', 'fin_prdt_cd', 'product_type')},
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=20)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=50)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.financialproduct')),
            ],
            options={
                'unique_together': {('product', 'intr_rate_type', 'save_trm')},
            },
        ),
    ]
