# Generated by Django 5.2.15 on 2026-06-19 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_preference', models.CharField(choices=[('mobile', '모바일 선호'), ('offline', '영업점 선호'), ('both', '상관없음')], max_length=30)),
                ('benefit_preference', models.CharField(choices=[('high_interest', '높은 금리 선호'), ('simple_condition', '간단한 조건 선호'), ('stability', '안정성 선호')], max_length=30)),
                ('stability_preference', models.CharField(choices=[('major_bank', '시중은행 선호'), ('internet_bank', '인터넷은행 선호'), ('no_preference', '상관없음')], max_length=30)),
                ('usage_purpose', models.CharField(choices=[('saving', '목돈 보관'), ('interest', '이자 수익'), ('short_term', '단기 운용')], max_length=30)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommended_results', to='products.bank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_test_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
